apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p3v5d9a66-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/p3v5d9a66-java-quarkus-gitops