apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p3v5d9a66-java-quarkus
  janus-idp.io/tekton: p3v5d9a66-java-quarkus
  backstage.io/kubernetes-id: p3v5d9a66-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p3v5d9a66-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
